services:
  db:
    image: mysql:8
    container_name: studyhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyhub
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    image: moonkwon/studyhub:latest
    container_name: studyhub-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: studyhub-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: studyhub-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 studyhub-app
    restart: always

volumes:
  mysql-data:

