services:
  db:
    image: mysql:8
    container_name: studyhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyhub
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    image: moonkwon/studyhub:latest
    container_name: studyhub-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:latest
    container_name: studyhub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: studyhub-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 studyhub-app
    restart: always

volumes:
  mysql-data:
